### ISSUE TITLE
bin/sh setup.sh fails on vanilla Ubuntu 14.04 server

### ISSUE THREAD

**Issue by graik** [igemsoftware/SYSU-Software-2015#28]
The blue pill seems to have an issue :)

vanilla Ubuntu 14.04 server edition:
    > bin/sh ./setup.sh 
    =====================================
    C.O.R.E Synbio Tool
    Brought to you by SYSU-Software 2015
    =====================================
    data/miniconda.sh: 15: data/miniconda.sh: 0: not found
    data/miniconda.sh: 65: data/miniconda.sh: Syntax error: word unexpected (expecting ")")

The "red pill" installation works fine though.

**Comment by leasunhy** [comment]
Sorry for the inconvenience :pray: 
We've tested the "blue pill" on a CentOS 7 server and an Archlinux Server, but wasn't able to cover Ubuntu...
We'll try to reproduce the problem and address the cause asap.
Thank you :laughing:

**Comment by leasunhy** [comment]
Okay, we've figured out that the problem was resulted from an old version of `/bin/sh` bundled in Ubuntu Server 14.04 LTS. We edited the shebang line in both scripts to make them use `/bin/bash` instead. During the debug, we've also found another problem...
Thank you! :-)
